<a href="https://colab.research.google.com/github/SiddhiInSync/MLP_GA/blob/main/GA1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("Week1_GA_dataset.csv")

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

What is the value present at the 692th indexed row and 0th indexed column in the data ?

In [ ]:
df.iloc[692, 0]

'2009-11-16'

What is the value present at the 546th indexed row and 7th indexed column in the data ?

In [ ]:
df.iloc[546,7]

np.int64(3)

How many unknown ("?) values are present in the dataset?

In [ ]:
df.isin(['?']).value_counts()

Date   Year   Locality  Estimated Value  Sale Price  Property  Residential  num_rooms  num_bathrooms  carpet_area  property_tax_rate  Face
False  False  False     False            False       False     False        False      False          False        False              False    8177
                                                     True      False        False      False          False        False              False    1823
Name: count, dtype: int64

What are the unique values present in the Locality feature of the dataset?

In [ ]:
df['Locality'].unique()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', nan,
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

Remove/Delete unknown ("?) values present in the dataset to make it null value.

In [ ]:
df.replace('?', np.nan, inplace=True)

Which of the following features have missing(NaN) values present in the dataset?

In [ ]:
Nan_val_per_column = df.isna().sum()
Nan_val_per_column

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

Which of the following feature has most missing(NaN) values present in the dataset?
 (Note: compute after removing "?")

In [ ]:
Nan_val_per_column.idxmax()

'Property'

Drop all the samples(rows) with missing values strictly greater than 2. How many samples remains after that ?

In [ ]:
df.loc[df.isna().sum(axis=1) <= 2].shape

(9917, 12)

Drop all the samples(rows) with missing values in the original dataframe. How many samples remains after that ?

In [ ]:
df.dropna()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
...,...,...,...,...,...,...,...,...,...,...,...,...
9986,2022-09-28,2022,Norwalk,305820.0,535000.0,Single Family,Detached House,3,2,1080.0,1.003979,West
9987,2022-09-28,2022,Norwalk,450510.0,677000.0,Single Family,Detached House,3,1,1000.0,1.003979,North
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East